name: Flutter CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            build/
            main/.dart_tool      
            main/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38'
          channel: stable


      - name: Install dependencies
      
        run: flutter pub get

      - name: Analyze
      
        run: flutter analyze

      

      - name: Build APK
      
        run: flutter build apk --release
      - name: Install Linux build dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - name: Build Linux
      
        run: flutter build linux --release
      
      
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: main/build/app/outputs/flutter-apk/app-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64-bundle
          path: main/build/linux/x64/release/bundle/
      - name: List directory recursively
        run: |
          echo "===== recursive file list ====="
          find . -type f | sort